### ISSUE TITLE
nestjs with apollo federation doesn't work

### ISSUE THREAD

**Issue by flyhigh-hifi** [profusion/apollo-federation-file-upload#23] opened 2021-02-22 12:45 UTC
Hi! I have tried to combine existing and working data source with file uploads and get errors on both graphql side - **(intermediate value).willSendRequest is not a function** and on the server – **RangeError: Maximum call stack size exceeded**

```
import { Module } from '@nestjs/common';
import { GATEWAY_BUILD_SERVICE, GraphQLGatewayModule } from '@nestjs/graphql';
import { RemoteGraphQLDataSource } from '@apollo/gateway';
import FileUploadDataSource from '@profusion/apollo-federation-upload';

const requestHeadersToForward: Array<string> = [
  'cookie',
  'user-agent',
];

class AuthenticatedDataSource extends FileUploadDataSource {
  async willSendRequest({ request, context }) {
    if (context.req?.headers) {
      super.willSendRequest({ request, context });
      requestHeadersToForward.forEach((h) => {
        if (context.req.headers[h]) {
          request.http.headers.set(h, context.req.headers[h]);
        }
      });
    }
  }

  async didReceiveResponse({ request, response, context }) {
    const cookie = response.http.headers.get('set-cookie');

    if (cookie) {
      context.res.set('set-cookie', cookie);
    }

    return response;
  }
}

@Module({
  providers: [
    {
      provide: AuthenticatedDataSource,
      useValue: AuthenticatedDataSource,
    },
    {
      provide: GATEWAY_BUILD_SERVICE,
      useFactory: (AuthenticatedDataSource) => {
        return ({ name, url }) => new AuthenticatedDataSource({ url });
      },
      inject: [AuthenticatedDataSource],
    },
  ],
  exports: [GATEWAY_BUILD_SERVICE],
})
class BuildServiceModule {}

@Module({
  imports: [
    GraphQLGatewayModule.forRootAsync({
      useFactory: async () => ({
        server: {
          cors: {
            credentials: true,
            allowedHeaders: ['Origin', 'X-Requested-With', 'content-type', 'set-cookie', 'cookie'],
            methods: ['GET, POST, OPTIONS, PUT, PATCH, DELETE'],
            origin: (requestOrigin, cb) => {
              if (!requestOrigin) return cb(null, '*');

              const origins = [/localhost/];
              if (origins.some((o) => o.test(requestOrigin))) {
                return cb(null, true);
              }
              cb(null, false);
            },
          },
          debug: true,
          context: ({ req, res }) => ({ req, res }),
        },
        gateway: {
          debug: true,
          serviceList: [],
        },
      }),
      imports: [BuildServiceModule],
      inject: [GATEWAY_BUILD_SERVICE],
    }),
  ],
})
export class GatewayModule {}

```

**Comment by flyhigh-hifi** [comment] 2021-02-22 17:38
Looks like it's not the issue with nestjs itself, here's a workaround https://github.com/MichalLytek/type-graphql/issues/37#issuecomment-592467594

**Comment by cabelitos** [comment] 2021-02-27 12:19
Hi, thank you for the bug report and sorry for the delay.


@flyhigh-hifi Did you manage to find a solution to your problem? The bug does not seem related to this package.

Also we never touch willSendRequest method, so it's highly unlikely that this is a bug on our end. However, if you could provide a reproducible example I could investigate what's happening.

**Comment by flyhigh-hifi** [comment] 2021-02-27 12:24
Yes, you are right, this is not related to your package. The solution was to replace internal apollo uploads with graphqlUploadExpress and the problem **Maximum call stack** in the fs-capacitor package has gone away.

**Comment by cabelitos** [comment] 2021-07-13 17:32
closing this since it's resolved

**Closed as completed by cabelitos** 2021-07-13 17:32 UTC

**Comment by bujosa** [comment] 2021-12-29 18:21
How I implement this on nestjs?
<img width="304" alt="image" src="https://user-images.githubusercontent.com/39348045/147692043-36d4dc5d-aa32-4305-bd28-e9753a740fbf.png">
